export interface HelpSection {
  id: string;
  title: string;
  content: string[];
}

export const QUICK_START: string[] = [
  "1. Drag an agent from the bottom bar onto the canvas",
  "2. Drag a second agent and connect them: green handle (right) → blue handle (left)",
  "3. Click a node to open the Inspector — edit model, soul, and tools",
  "4. Click ▶ Run (green button, bottom-left) to execute the pipeline",
];

export const HELP_SECTIONS: HelpSection[] = [
  {
    id: "getting-started",
    title: "Getting Started",
    content: [
      "MultiClawProtocol is a visual drag-and-drop AI agent pipeline builder.",
      "Key concepts:",
      "• Agent — an AI worker with a model, a soul (personality), and tools",
      "• Pipeline — a directed graph of agents connected by typed edges",
      "• Soul — the agent's SOUL.md file defining role, goal, and constraints",
      "• Execution — the engine walks the graph, fires each agent in order",
      "",
      "System Requirements: Linux (Ubuntu 24.04+), 16GB+ RAM, GPU recommended for local models.",
    ],
  },
  {
    id: "pipeline",
    title: "Pipeline Page",
    content: [
      "The Pipeline page is the main workspace with 4 regions:",
      "• Canvas (center) — infinite drag-and-drop plane for building pipelines",
      "• Agent Palette (bottom) — scrollable row of all available agents",
      "• Inspector (right) — config, soul, schema, logs for the selected agent",
      "• Execution Controls (bottom-left) — Run, Pause, Stop + autonomy mode",
      "",
      "Canvas controls:",
      "• Pan — middle-click drag or Space+drag",
      "• Zoom — scroll wheel",
      "• Add agent — drag from bottom palette onto canvas",
      "• Remove agent — click the X button on the node",
      "• Connect — drag from green output handle to blue input handle",
    ],
  },
  {
    id: "inspector",
    title: "Inspector Panel",
    content: [
      "Click any agent node to open the Inspector (right panel). Four tabs:",
      "",
      "Config — change model, temperature, max tokens, isolation mode, tools",
      "Soul — edit Role, Goal, and Constraints (saves on blur)",
      "Schema — view payload types and I/O schemas",
      "Logs — execution logs filtered by this node",
      "",
      "Click the ▸ arrow to collapse/expand the Inspector.",
    ],
  },
  {
    id: "agents",
    title: "The 18 Base Agents",
    content: [
      "The Brain (blue): STRATEGIST, INTEL, LEGAL-EXPERT — strategy and research",
      "The Forge (green): CODEREVIEW, BUILDER, BORIS, GITHUB-SCOUT — code and QA",
      "The Hustle (amber): SALES&CLOSER, MARKETER, DTF-EXPERT — sales and marketing",
      "Solo (purple): ORCHESTRATOR, PROXY, SENTINEL, DESIGNER, SPEC-LOADER",
      "Supervisors (red): BRAIN-SUPERVISOR, FORGE-SUPERVISOR, HUSTLE-SUPERVISOR",
      "",
      "Each agent has a default model, soul, and tool set. All are configurable.",
    ],
  },
  {
    id: "souls",
    title: "Editing Agent Souls",
    content: [
      "A SOUL.md defines the agent's personality — it's injected as the system prompt.",
      "",
      "To edit: click agent on canvas → Soul tab in Inspector",
      "• Role — the agent's job title and identity",
      "• Goal — what the agent is trying to achieve",
      "• Constraints — hard rules (one per line)",
      "",
      "Changes save automatically when you click away.",
      "The new soul takes effect on the next agent invocation.",
    ],
  },
  {
    id: "custom-agents",
    title: "Adding Custom Agents",
    content: [
      "1. Drag any base agent onto the canvas",
      "2. Click it → Config tab → change the Name",
      "3. Select a different model from the dropdown",
      "4. Switch to Soul tab → rewrite Role, Goal, Constraints",
      "5. The customized agent is saved in the pipeline file",
      "",
      "Tip: start from the agent whose team matches your intent.",
      "BUILDER for code tasks, INTEL for research, DESIGNER for UI work.",
    ],
  },
  {
    id: "settings",
    title: "Settings Page",
    content: [
      "API Keys: OpenRouter (3 pools), Anthropic, OpenAI, Google AI, Grok, Mistral, Ollama, LiteLLM",
      "Keys stored locally on your device — never sent to any server.",
      "",
      "Local Models: auto-scans Ollama for installed models",
      "Cloud Models: shows available models with pricing and key status",
      "Profile: edit display name, view auth provider",
    ],
  },
  {
    id: "3d-map",
    title: "3D Map",
    content: [
      "Interactive 3D force-directed graph of all 18 agents.",
      "• Drag to rotate, scroll to zoom",
      "• Nodes colored by team (blue, green, amber, purple, red)",
      "• Edges show agent relationships",
      "• Hover for agent info tooltip",
    ],
  },
  {
    id: "terminal",
    title: "Terminal",
    content: [
      "Built-in terminal with MultiClawProtocol commands:",
      "",
      "  help              — show available commands",
      "  help tutorial      — quick-start guide",
      "  help agents        — agent team overview",
      "  help models        — model routing table",
      "  help keys          — API key setup",
      "  agents             — list all registered agents",
      "  status             — check Ollama and LiteLLM connectivity",
      "  ollama list        — list installed local models",
      "  ollama ps          — show models loaded in VRAM",
      "  clear              — clear terminal",
    ],
  },
  {
    id: "logs",
    title: "Log Viewer",
    content: [
      "Shows agent errors, token usage, killswitch events, and pipeline logs.",
      "• Filter by level (error/warn/info/debug)",
      "• Filter by source (hermes, openrouter, ollama, docker, killswitch)",
      "• Filter by agent name",
      "• Search text across all fields",
      "• Stats bar: error count, warning count, total cost",
    ],
  },
  {
    id: "models",
    title: "Model Routing",
    content: [
      "Each agent can use a different model. Available tiers:",
      "",
      "  Free      Qwen 3.6+              $0/$0",
      "  Free      Gemma 4 26B (Ollama)    $0/$0",
      "  Budget    Qwen3 32B              $0.08/$0.24",
      "  Budget    Gemma 4 26B            $0.13/$0.40",
      "  Mid       DeepSeek V3.2          $0.28/$0.42",
      "  Premium   GLM 5V Turbo           $1.20/$4.00",
      "  Elite     Claude Sonnet 4.5      $3/$15",
      "",
      "Change model: click agent → Config tab → Model dropdown",
    ],
  },
  {
    id: "shortcuts",
    title: "Keyboard Shortcuts",
    content: [
      "  Delete     Remove selected node",
      "  Space      Fit all nodes in viewport",
      "  Ctrl+S     Save pipeline",
      "  Ctrl+R     Run pipeline",
      "  Escape     Deselect / close Inspector",
    ],
  },
];
